//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string DesTitle { get; set; }
        public string Desc { get; set; }
        public string BarTitle { get; set; }
        public string BarDesc { get; set; }
        public string Bar1 { get; set; }
        public string Bar2 { get; set; }
        public string Bar3 { get; set; }
        public string Bar4 { get; set; }
        public Nullable<int> Bar1Per { get; set; }
        public Nullable<int> Bar2Per { get; set; }
        public Nullable<int> Bar3Per { get; set; }
        public Nullable<int> Bar4Per { get; set; }
        public string ButtonLeft { get; set; }
        public string ButtonRight { get; set; }
    }
}
