//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomePage()
        {
            this.HomeSlideTexts = new HashSet<HomeSlideText>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string TitlePart2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeSlideText> HomeSlideTexts { get; set; }
    }
}
