//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollisEntities : DbContext
    {
        public CollisEntities()
            : base("name=CollisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<HomePage> HomePages { get; set; }
        public virtual DbSet<HomeSlideText> HomeSlideTexts { get; set; }
        public virtual DbSet<LogoNavBar> LogoNavBars { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PageTitle> PageTitles { get; set; }
        public virtual DbSet<Protofilio> Protofilios { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SocialSite> SocialSites { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
    }
}
